### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by hungnguyen2611** [Zheng-Chong/CatVTON#10]
Thanks for open-sourcing this work! I have a concern about the quantitative results reported in the paper. I used the [vitonhd-16k-512](https://huggingface.co/zhengchong/CatVTON/tree/main/vitonhd-16k-512) checkpoint to evaluate on VITON-HD, but the results did not match those reported in the paper, specifically I got LPIPS=0.1019, SSIM=0.8649, FID=13.5417(unpair), KID=6.748(unpair), which is relatively low compared to the paper report.

**Comment by Zheng-Chong** [comment]
I am uncertain if there are discrepancies in your reasoning process and metric calculations. 
However, for 512-level inference, to replicate the results from the article, ensure that `--repaint` is activated. This is due to the inherent tendency of VAEs to diminish image detail quality and induce color shifts, particularly at lower resolutions. As a result, repainting non-garment areas is necessary, a post-processing technique employed by numerous diffusion-based methods. Furthermore, for the computation of FID and KID metrics, we utilize 'cleanfid'; for other metrics, we employ 'torchmetrics'. Variations across different codebases may also engender discrepancies.

**Comment by hungnguyen2611** [comment]
Thanks for your reply.
- For 512-level inference, I confirm that the --repaint option is activated for repainting non-garment areas.
- The repository I used to calculate the results is from [LaDI-VTON](https://github.com/miccunifi/ladi-vton/blob/master/src/utils/val_metrics.py). It also utilizes [cleanfid](https://github.com/GaParmar/clean-fid) and [torchmetrics](https://lightning.ai/docs/torchmetrics/stable/). 
I ran the following code to get the VITON-HD result without changing anything in ur codebase
```
CUDA_VISIBLE_DEVICES=0 python inference.py \
--dataset vitonhd \
--data_root_path <path/to/vitonhd> \
--output_dir <path> 
--dataloader_num_workers 8 \
--batch_size 8 \
--seed 555 \
--mixed_precision fp16 \
--allow_tf32 \
--repaint \
--eval_pair  
```

**Comment by Zheng-Chong** [comment]
Thank you for raising this issue. 
We will redeploy and test using the latest submission in this project to see if there is any problems with the code or other materials we provided which may lead to the discrepancies in evaluation.

**Comment by Zheng-Chong** [comment]
SSIM: 0.8681719899177551
FID: 5.437834693735738
KID: 0.42015367617613264
LPIPS: 0.057613495737314224

**Comment by Zheng-Chong** [comment]
We have tested the VTONHD paired data using the latest commit code, and the results show very subtle differences from what we reported, with some metrics improving and some getting worse, but no significant performance difference is observed.
| Metric | Code Test | Paper |
|---------|-----------|-------|
| SSIM    | 0.8681719899177551 | 0.8704070448875427 |
| FID     | 5.437834693735738   | 5.425168616063701   |
| KID     | 0.42015367617613264 | 0.4253343618618783  |
| LPIPS   | 0.057613495737314224 | 0.056472521275281906 |

We believe this is due to the randomness in the two inferences.
(Additionally, the first time we calculated the metrics, we adopted the method of generating all results first and then repainting. The reorganized code integrates repainting into each generation. Although there is theoretically no difference between the two, this part may also be a reason for the certain differences.)

If you need, we can provide the result images from these two inferences.

**Comment by hungnguyen2611** [comment]
Thanks for providing a detailed evaluation. I already pulled the latest commit and retested it; however, there are still no significant differences from the old result. I uploaded the results of VITON-HD [here](https://drive.google.com/drive/folders/1LSyn94HRI_Y8ufazQbkd0jvHI-eUN6sR?usp=sharing). Could you please check and evaluate them? I'm not sure if there's something wrong with how I computed the metrics or with the inference process. Thanks!!

**Comment by Zheng-Chong** [comment]
> We have tested the VTONHD paired data using the latest commit code, and the results show very subtle differences from what we reported, with some metrics improving and some getting worse, but no significant performance difference is observed.
> 
> Metric	Code Test	Paper
> SSIM	0.8681719899177551	0.8704070448875427
> FID	5.437834693735738	5.425168616063701
> KID	0.42015367617613264	0.4253343618618783
> LPIPS	0.057613495737314224	0.056472521275281906
> We believe this is due to the randomness in the two inferences. (Additionally, the first time we calculated the metrics, we adopted the method of generating all results first and then repainting. The reorganized code integrates repainting into each generation. Although there is theoretically no difference between the two, this part may also be a reason for the certain differences.)
> 
> Perhaps you could clone the latest repository and retest it? If you need, we can provide the result images from these two inferences.

**Comment by Zheng-Chong** [comment]
I tried to calculate the metrics of the 512 results with the 1024 dataset, and got FID: 10.263875185672163, KID: 6.036994466966962, which are similar to the results you reported.
 Maybe this is the reason for the difference?

**Comment by hungnguyen2611** [comment]
> I tried to calculate the metrics of the 512 results with the 1024 dataset, and got FID: 10.263875185672163, KID: 6.036994466966962, which are similar to the results you reported. Maybe this is the reason for the difference?

Yes, those are the FID and KID scores I got. Is there anything wrong with how I'm evaluating them?

**Comment by Zheng-Chong** [comment]
> > I tried to calculate the metrics of the 512 results with the 1024 dataset, and got FID: 10.263875185672163, KID: 6.036994466966962, which are similar to the results you reported. Maybe this is the reason for the difference?
> 
> Yes, those are the FID and KID scores I got. Is there anything wrong with how I'm evaluating them?

You need to resize the VITONHD dataset to 512x384, and then calculate the metrics with the obtained 512 results, otherwise the misalignment of the image sizes will lead to deterioration of the metrics.

**Comment by Zheng-Chong** [comment]
> > > I tried to calculate the metrics of the 512 results with the 1024 dataset, and got FID: 10.263875185672163, KID: 6.036994466966962, which are similar to the results you reported. Maybe this is the reason for the difference?
> > 
> > 
> > Yes, those are the FID and KID scores I got. Is there anything wrong with how I'm evaluating them?
> 
> You need to resize the VITONHD dataset to 512x384, and then calculate the metrics with the obtained 512 results, otherwise the misalignment of the image sizes will lead to deterioration of the metrics.

Is that working for your problem?

**Comment by hungnguyen2611** [comment]
Oh, I figured it out. The `make_custom_stats` function in [LaDI-VTON](https://github.com/miccunifi/ladi-vton/blob/master/src/utils/generate_fid_stats.py#L9) reused the statistics from my recent evaluation at the 1024 level. Now, everything works and aligns with your reported results.

| Metric | Code Test | Paper |
|--------|-----------|-------|
| SSIM   | 0.8682    | 0.8704 |
| FID    | 5.4539    | 5.4252 |
| KID    | 0.4       | 0.4253 |
| LPIPS  | 0.0962    | 0.0565 |

Thanks for correcting me 🙇‍♂️. I appreciate your work!

**Comment by Zheng-Chong** [comment]
I am also very happy to help you solve the problem. 
This issue may help others get the correct result in the future. Thanks!

**Comment by ZhangLei999** [comment]
@Zheng-Chong 
There are some issues with some of your inference code.
In the repaint function, shouldn't mask_np only contain two values（0 and 1）?
After mask_np = np.array(mask) / 255, it contains 255 different values ranging from 0 to 1
